name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verilator:
    name: verilator regression
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install build dependencies
      run:  sudo apt-get install -y git make autoconf g++ flex bison libfl2 libfl-dev
    - name: Cache verilator
      uses: actions/cache@v2
      id:   cache-verilator
      with:
        path: verilator-4.103
        key: ${{ runner.os }}-verilator-4.103
    - name: Compile Verilator
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      run: |
        wget https://github.com/verilator/verilator/archive/refs/tags/v4.103.zip
        unzip v4.103.zip
        cd verilator-4.103
        autoconf
        ./configure
        make
    - name: Install Verilator
      run: |
        cd verilator-4.103
        sudo make install
        verilator --version
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Test
      run: sbt test
      
