name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verilator:
    name: verilator regression
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Verilator
      run:  sudo apt-get install verilator
    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.8
    - name: Test
      run: sbt test
      
